### ISSUE TITLE
Fork me on github image not available; showing alt text

### ISSUE THREAD

**Issue by thisisnian** [codersociety/codersociety.github.com#5]
The fork me on github image is no longer available and shows the image not found square box with the x.

What you could do is save a picture in one of your directories and link to it locally, rather than relying on a third party's uptime. 

I haven't made any changes to the code, thought you'd want to pick an image yourself. But as a reference it's on _layouts/default.html

**Comment by Adron** [comment]
Closing as plans are changing around this organization.
